# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  agent_name: "Hosted Agent"
  version: ci
  appVersion: '2.0'
  appBuild: ${{github.run_number}}
  appRevision: 0

defaults:
  run:
    shell: PowerShell

    # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run pipeline
        env:
          InsiderSasToken: ${{ secrets.InsiderSasToken }}
          LicenseFile: ${{ secrets.LicenseFile }}
        run: scripts\DevOps-Pipeline.ps1 -version ${{env.version}} -appBuild ${{env.appBuild}} -appRevision ${{env.appRevision}}

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          check_name: Test Results
          comment_title: Test Statistics
          hide_comments: all but latest
          comment_on_pr: true
          files: testresults*.xml
          report_individual_runs: true
          deduplicate_classes_by_file_name: false
