# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  version: ci
  appVersion: '2.0'
  appBuild: ${{github.run_number}}
  appRevision: 0

defaults:
  run:
    shell: PowerShell

    # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run pipeline
        env:
          InsiderSasToken: ${{ secrets.InsiderSasToken }}
          LicenseFile: ${{ secrets.LicenseFile }}
        run: scripts\DevOps-Pipeline.ps1 -version ${{env.version}} -appBuild ${{env.appBuild}} -appRevision ${{env.appRevision}}

      - name: Publish Test Results
        uses: mikepenz/action-junit-report@v1
        with:
          report_paths: 'testresults*.xml'
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cleanup
        if: always()
        run: scripts\Cleanup.ps1
